### ISSUE TITLE
Add a variable for pull request creator

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-stash#13]
It would be great if we had a variable for the pull request creator so we can pass it to Jenkins (or another CI tool)

**Comment by tomasbjerre** [comment]
I added these variables
* ${PULL_REQUEST_AUTHOR_DISPLAY_NAME} Example: Administrator
* ${PULL_REQUEST_AUTHOR_EMAIL} Example: admin@example.com
* ${PULL_REQUEST_AUTHOR_ID} Example: 1
* ${PULL_REQUEST_AUTHOR_NAME} Example: admin
* ${PULL_REQUEST_AUTHOR_SLUG} Example: admin
