### ISSUE TITLE
Jenkins is trying to authenticate even when no user/pass set

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-stash#16]
Even when I leave the username and password blank, it seems to send something to Jenkins in the Authorization header. Here is the error from the Jenkins log:

```
org.acegisecurity.BadCredentialsException: Empty password
```

Additionally, the Stash log says that it got a 401. If I switch the log to debug I get:

```
2015-04-09 18:25:26,740 INFO  [AtlassianEvent::thread-1]  se.bjurr.prnfs.listener.UrlInvoker Url: "<our jenkins url>" user: "" password: ""
```

**Comment by tomasbjerre** [comment]
Yes thats correct, I fixed it now.
