### ISSUE TITLE
Add an event to fire only when the FROM_HASH changes

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-stash#17]
Currently the RESCOPED event covers either the TO_HASH or FROM_HASH changing. The former happens when somebody updates the target branch (e.g. merges something else in) and the latter when somebody updates the source branch (e.g. fixes some code review feedback).

We have a large dev team and our destination branches change frequently. This in turn means that we get RESCOPE events all the time even though the PR contents haven't changed in a meaningful way. While I understand that in theory we should "fire" a new Jenkins job, running our build and test is quite expensive so we want to limit it to only when the FROM_HASH changes.

This can be done by checking the events `getPreviousFromHash()` and `getPreviousToHash()` against the current values. If `getPreviousFromHash()` changed - invoke the URL, and if it hasn't, don't.

**Comment by tomasbjerre** [comment]
Ok. I'll probably add a couple of new event types for this.
* RESCOPED_FROM
* RESCOPED_TO

And implement it something like this:
 @EventListener
 public void onEvent(final PullRequestRescopedEvent e) {
  handleEvent(new PullRequestEvent(e.getSource(), e.getPullRequest(), e.getAction()) {
   @Override
   public PullRequestAction getAction() {
    if (e.getPreviousToHash().equals(e.getPullRequest().getToRef().getLatestChangeset())) {
     return "RESCOPED_FROM";
    } else if (e.getPreviousFromHash().equals(e.getPullRequest().getFromRef().getLatestChangeset())) {
     return "RESCOPED_TO";
    } else {
     return super.getAction();
    }
   }
  });
 }

I'll fix it later today.

**Comment by itay** [comment]
I think you want a not equals for the above - if the prev from hash does not equal the new from hash then it is rescoped from, and then if the prev to hash is not equal to the new to hash, then it is rescoped to.

**Comment by tomasbjerre** [comment]
This should fix the issue:
https://github.com/tomasbjerre/pull-request-notifier-for-stash/commit/fd4e411b7d7240b60abcc80d58d081dac0affbe6

**Comment by tomasbjerre** [comment]
I dont have a Stash server to test this on. And the one in Atlassian SDK only permits a few commits before they are blocked... So I'll trust the junit tests and will now make a release with this included.

**Comment by itay** [comment]
I just wanted to let you know that this works great - this is awesome.

**Comment by derekln1** [comment]
Awesome, was looking for this too!

Thanks a lot!

**Comment by derekln1** [comment]
I just installed and tested 1.7, does the ${PULL_REQUEST_ACTION} supposed to return "RESCOPED_TO" and "RESCOPED_FROM"?  I always get "RESCOPED".

I have an existing pull request open and whether i just push a new commit to the source/from branch or the target/to branch, ${PULL_REQUEST_ACTION} returns "RESCOPED".

Thanks,
Derek

**Comment by tomasbjerre** [comment]
I'll fix that so it returns RESCOPED_FROM and RESCOPED_TO

**Comment by derekln1** [comment]
I merged the commit on master that has this, created a build and tested it.  It works now I can see the RESCOPED_FROM and RESCOPED_TO returned, except that I see 2 triggers sent for a RESCOPED_TO event.

When I update the target/to branch of an open pull request, 2 http requests are sent each with a different ${PULL_REQUEST_FROM_HASH}.  One will contain the from commit of the source branch and the other will contain the previous commit of the target branch.

Is it possible to just trigger one http request with the PULL_REQUEST_FROM_HASH being the commit of the source branch?  Let me know if I should open an Issue.

Thanks again for the support :)

**Comment by derekln1** [comment]
Would it be possible to use PullRequestService and PageUtils to get the changesets/commits on the pull request?  Maybe like this?

Page<Changeset> pageChanges = pullRequestService.getChangesets(rescopedEvent.getPullRequest().getToRef().getRepository().getId(),rescopedEvent.getPullRequest().getId(),PageUtils.newRequest(0, 99));

Then return a RESCOPED_TO event only if the FromHash is part of the pull request changesets/commits?

Thanks,
Derek

**Comment by tomasbjerre** [comment]
Interesting. I would like you to open an issue for this.

I would like to debug it a bit, but I dont have a Stash instance to test it on. And the one in the SDK does not accept pushing any more commits on my installation.

**Comment by derekln1** [comment]
#20 Opened.  Thanks Tomas.  I can help test when you have something.
