### ISSUE TITLE
Add HTTP POST request support

### ISSUE THREAD

**Issue by derekln1** [tomasbjerre/pull-request-notifier-for-stash#18]
When triggering my Jenkins build, i need to initiate a POST request.  It looks like the current plugin only is sending a GET request.  Can you add support for HTTP POST requests?

I'm not a JAVA guy but got this working with java.net.HttpURLConnection

In UrlInvoker.java, i replaced:
   final URLConnection uc = url.openConnection();

With:
   final HttpURLConnection uc = (HttpURLConnection) url.openConnection();
   uc.setRequestMethod("POST");

Seemed to work for me, but again not a JAVA guy and also some people may want "GET" requests as well.

Thanks,
Derek

**Comment by tomasbjerre** [comment]
Nice feature =) I'm adding it like this:
https://github.com/tomasbjerre/pull-request-notifier-for-stash/commit/e482e902c2d7e94597b809c4e92a689e4876ce14

**Comment by tomasbjerre** [comment]
I'll make a release with this now, hope it works =)

**Comment by derekln1** [comment]
Looks good.
I merged the commit on master that has this fix in my local workspace, created a build, installed and tested that I could send a POST request and I was able to successfully.
Thanks for the great support :)
