### ISSUE TITLE
new variable containing only name of branch

### ISSUE THREAD

**Issue by sheuser** [tomasbjerre/pull-request-notifier-for-stash#21]
I really like this plugin, and would like to use it to integrate our Stash installation better with the CI services provided by [Scrutinizer](https://scrutinizer-ci.com/).

Unfortunately, their API only accepts simple branch names instead of refs like `${PULL_REQUEST_FROM_ID}` provides.

Would it be possible to implement a new variable (something like `${PULL_REQUEST_FROM_BRANCH}` perhaps) that contains only the name of the branch?

If the Stash API does not provide a convenient method and you have to resort to chopping off the first part of the string, please look out for those of us with slashes in their branch names.

Thanks in advance!

**Comment by tomasbjerre** [comment]
This is now available in version 1.10 =)
