### ISSUE TITLE
Allow creating custom POST bodies and custom headers

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-stash#22]
It would be nice if when configured to be in POST mode, there could be a place to put in a template that would have the variables and would be "replaced".

For example, I might have the following POST body if you wanted to send JSON:
```
{
  "from_hash": ${FROM_HASH},
  "to_hash": ${TO_HASH},
  ...
}
```

or if you wanted to send form encoding:
```
from_hash=${FROM_HASH}&to_hash=${TO_HASH}&...
```

In addition, it would be nice to be able to specify custom headers, in case you are trying to send to an API that uses OAuth and not Basic Auth, for example.

**Comment by tomasbjerre** [comment]
The "post content" textarea here:
https://github.com/tomasbjerre/pull-request-notifier-for-stash/blob/master/sandbox/closer.png
Supports variables. So that feature already exists =) Or do you mean something else?

Headers can definitely be added! I'll implement it next.

**Comment by itay** [comment]
Huzzah - I'm just blind. I don't have the latest version.

If you add just add custom headers, I'm all set :)

**Comment by tomasbjerre** [comment]
=) I started working on it here:
https://github.com/tomasbjerre/pull-request-notifier-for-stash/commit/1ffaa81ca622e24e07048a142f3e5c8d2dd2620e
I'll probably have time to finish it tomorrow.

**Comment by tomasbjerre** [comment]
Custom headers should work now, in pull-request-notifier-for-stash-1.11
