### ISSUE TITLE
Mark the plugin as supporting Stash DC 

### ISSUE THREAD

**Issue by itay** [tomasbjerre/pull-request-notifier-for-stash#24]
Currently the plugin is marked as not supporting Stash DC, but we run it in a Stash DC environment and it works fine. A quick audit of the code also makes me think it should work just fine as well.

**Comment by tomasbjerre** [comment]
Ok, thanks for noticing! I'll mark it as compatible in next release =)

**Comment by tomasbjerre** [comment]
This should work now, in pull-request-notifier-for-stash-1.11
