### ISSUE TITLE
Filter regexp special escape characters not working?

### ISSUE THREAD

**Issue by derekln1** [tomasbjerre/pull-request-notifier-for-stash#27]
Hopefully i didn't miss something but i'm trying to match my "keyword" in the pull request comment to trigger a job.  I want to be able to match my "keyword" and ignore spaces before and after.

Filter string:  ${PULL_REQUEST_TO_ID}:${PULL_REQUEST_COMMENT_TEXT}:
Filter regexp:  .*:(\s*keyword\s*|):

It only seems to match if i enter in the exact "keyword" as a comment without any spaces before and after the "keyword".  I also tried with \n in my regexp, but again no match unless it was just "keyword" entered as a comment.  Maybe Stash is stripping these characters?

**Comment by tomasbjerre** [comment]
Did you try this site?
http://jex.im/regulex/#!embed=false&flags=&re=.%3A(%5Cskeyword%5Cs*%7C)%3A
Perhaps this is what you want?
http://jex.im/regulex/#!embed=false&flags=&re=.*keyword.*

**Comment by tomasbjerre** [comment]
I have made a few tests by invoking URL
bjurrs.se/?${PULL_REQUEST_TO_ID}:${PULL_REQUEST_COMMENT_TEXT}:
And then checking the Apache log to see what it evalueates to. It seems to me that it is working. Reply with the evaluated value of "${PULL_REQUEST_TO_ID}:${PULL_REQUEST_COMMENT_TEXT}:" that should match the regexp, and I'll have a look at it.

**Comment by derekln1** [comment]
hi Tomas,

Neither of your regexp suggestions worked for me.  How should I reply with the evaluated value?  Can you give an example how to get that?

Here is the configuration of the plugin via rest:
[[{"name":"FORM_IDENTIFIER","value":"7287881157309288335"},{"name":"filter_string","value":"${PULL_REQUEST_TO_ID}:${PULL_REQUEST_COMMENT_TEXT}:"},{"name":"filter_regexp","value":".*:(\\s*pre-merge-build-please\\s*|):"},{"name":"events","value":"COMMENTED"},{"name":"events","value":"OPENED"},{"name":"events","value":"RESCOPED_FROM"},{"name":"user","value":"mylogin"},{"name":"password","value":"XXXXXXXXXX"},{"name":"proxy_user","value":""},{"name":"proxy_password","value":""},{"name":"proxy_server","value":""},{"name":"proxy_port","value":""},{"name":"header_name","value":""},{"name":"header_value","value":""},{"name":"header_base64","value":"NO"},{"name":"url","value":"http://il01lab4009.am.mot.com:8080/job/pull_request_handler/buildWithParameters?sourceBranch=${PULL_REQUEST_FROM_BRANCH}&targetBranch=${PULL_REQUEST_TO_BRANCH}&pullRequestId=${PULL_REQUEST_ID}&projectKey=${PULL_REQUEST_FROM_REPO_PROJECT_KEY}&repoName=${PULL_REQUEST_FROM_REPO_NAME}&repoId=${PULL_REQUEST_FROM_REPO_ID}&fromCommit=${PULL_REQUEST_FROM_HASH}&toCommit=${PULL_REQUEST_TO_HASH}&pullRequestAction=${PULL_REQUEST_ACTION}&pullRequestComment=\"${PULL_REQUEST_COMMENT_TEXT}\""},{"name":"method","value":"POST"},{"name":"post_content","value":""}]]

Thanks,
Derek

**Comment by tomasbjerre** [comment]
You can invoke some webserver where you have access to the logs. In my case I would remove the filter and then have the plugin invoke:
http://bjurr.se/?${PULL_REQUEST_TO_ID}:${PULL_REQUEST_COMMENT_TEXT}:
And then check the log to see what "${PULL_REQUEST_TO_ID}:${PULL_REQUEST_COMMENT_TEXT}:" was evaluated to.

**Comment by derekln1** [comment]
sorry... you're right.  it is matching the regexp... checking the atlassian log it is matching the spaces and newlines (if i add that to my regexp).  For example if i use:
.*:([\s\n]*pre-merge-build-please[\s\n]*|):

It is matching.  The problem is that the space or newline causes the constructed URL to fail, as the space or newline creates an "Illegal character in the URL".  For example:  http://myjenkins/job/myjob/buildWithParameters?pull_request_comment=mykeyword is valid
http://myjenkins/job/myjob/buildWithParameters?pull_request_comment="   mykeyword" is not valid

I don't think there is a way send the POST body content to Jenkins, otherwise I could probably send a comment with spaces/newlines using the POST body content.  I'll check around.  If I can't find a way to do it, it's not a big deal.

Thanks for the support.

**Comment by tomasbjerre** [comment]
Since 1.11 that space should be replaced by "%20" and make a valid URL. Which version do you have?

**Comment by derekln1** [comment]
I upgraded to 1.12.  I was using a snapshot build/commit of 1.11 before.

Working now.  Thanks Tomas.
