### ISSUE TITLE
Add new variables for SSH and HTTP clone URL source and target branch

### ISSUE THREAD

**Issue by christiangalsterer** [tomasbjerre/pull-request-notifier-for-stash#28]
Please add new variables for the SSH and HTTP clone URL for the source and target branch e.g.
PULL_REQUEST_FROM_SSH_CLONE_URL
PULL_REQUEST_FROM_HTTP_CLONE_URL
PULL_REQUEST_TO_SSH_CLONE_URL
PULL_REQUEST_TO_HTTP_CLONE_URL

This would allow to directly call the [Jenkins Git Plugin Notification feature](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin#GitPlugin-Pushnotificationfromrepository) from the plugin without an intermediate step, e.g. a Jenkins job which adds the SSH/HTTP URL respectively.

PS: Really great plugin. We use it since the first version and are building already +100 repositories and +300 Jenkins builds with it without a hazzle. Was waiting for a long time for this and also filed a request to Atlassian but no progress there.

**Comment by tomasbjerre** [comment]
Sounds good :) I saw your fork, will you implement it?

**Comment by christiangalsterer** [comment]
Just looking into it to see what is possible in the next hours. Will let you know if I can do it.

**Comment by christiangalsterer** [comment]
Ok, so it looks like that it is a little bit more work needed then originally hoped for. In order to get the clone URL one uses a RepositoryService.getCloneLinks() implementation. Currently resolving all the trigger values is done in PrnfsRenderer.PrnfsVariable with an anonymous Resolver. This needs to be changed but this is more work then I have time until at least Wednesday. So if you have time and are in the mood I would appreciate if you can implement this. If I have more time then currently expected, I will let you know.

**Comment by christiangalsterer** [comment]
Actually found some more free time, so just about to start implementing

**Comment by christiangalsterer** [comment]
PR request available at https://github.com/tomasbjerre/pull-request-notifier-for-stash/pull/29

**Comment by tomasbjerre** [comment]
I made a quick review and it looks good. Nice work! I'll merge it tomorrow. I'll also add some test cases.

**Comment by christiangalsterer** [comment]
Great!

**Comment by tomasbjerre** [comment]
I pushed some test cases for this now. I'll have a look at it, on a real Stash instance, later and then make a release.

**Comment by tomasbjerre** [comment]
This is now released in 1.12
