### ISSUE TITLE
Branch names with "/" truncated in ${PULL_REQUEST_FROM_BRANCH} and ${PULL_REQUEST_TO_BRANCH}

### ISSUE THREAD

**Issue by ztaf** [tomasbjerre/pull-request-notifier-for-stash#31]
Thanks for this super nice plugin!
 
I have an issue with the following branch name of mine: "feature/QLC-1136-email-greeting".

Everything before the "/" is cutted out, thus the ${PULL_REQUEST_FROM_BRANCH} says my branch name is "QLC-1136-email-greeting" and not "feature/QLC-1136-email-greeting"

**Comment by tomasbjerre** [comment]
Can you use PULL_REQUEST_FROM_ID and PULL_REQUEST_TO_ID instead?

**Comment by ztaf** [comment]
Thanks for quick reply. 
...Sure...no worries... the PULL_REQUEST_FROM_ID and PULL_REQUEST_TO_ID is fine right now 
:-)

**Comment by tomasbjerre** [comment]
Ok, only fine? =) If there is a use case where you must have "feature/QLC-1136-email-greeting" and not "refs/heads/feature/QLC-1136-email-greeting", then maby it should be added.

**Comment by ztaf** [comment]
Ok nice!
:-)

**Comment by christiangalsterer** [comment]
I actually would have the need the PULL_REQUEST_FROM_BRANCH/PULL_REQUEST_TO_BRANCH is the complete branch name and not only part after the last "/". So would be nice to get this fixed.

**Comment by christiangalsterer** [comment]
I quickly checked the code and it should be to hard to fix and I will provide a bug fix soon.

**Comment by tomasbjerre** [comment]
Yes, should be as simple as adding:
${PULL_REQUEST_FROM_DISPLAY_ID} => pullRequestEvent.getPullRequest().getFromRef().getDisplayId() 
and
${PULL_REQUEST_TO_DISPLAY_ID} => pullRequestEvent.getPullRequest().getToRef().getDisplayId()

**Comment by christiangalsterer** [comment]
Actually I think that the existing PULL_REQUEST_FROM_BRANCH/PULL_REQUEST_TO_BRANCH should be fixed as they only return the last part of the branch name and not the complete/correct name, i.e. this is a bugfix

**Comment by tomasbjerre** [comment]
Ok you are right @christiangalsterer. So the solution here is to let .._BRANCH reolve to pullRequestEvent.getPullRequest().getFrom/ToRef().getDisplayId()

**Comment by christiangalsterer** [comment]
Will commit a PR soon...

**Comment by tomasbjerre** [comment]
Nice job! This is now i 1.13 =)

**Comment by christiangalsterer** [comment]
Thx ;-) Great that you made already a release.

**Comment by ztaf** [comment]
Many Thx from me too! ;-)
