### ISSUE TITLE
No notification/duplicate notification sent for changes in target branch and partially wrong PULL_REQUEST_FROM_HASH

### ISSUE THREAD

**Issue by christiangalsterer** [tomasbjerre/pull-request-notifier-for-stash#34]
I think I found two scenarios where no notification was sent or where two notifications were sent with PULL_REQUEST_FROM_HASH having an incorrect value:
 
Here the test setup.
 
Test 1:
RESCOPED_FROM activated
RESCOPED_TO activated
Change on source branch
Result: Correct trigger with PULL_REQUEST_FROM_HASH containing the correct SHA from the commit on the source branch
 
Test 2:
RESCOPED activated
Change on source branch
Result: Correct trigger with PULL_REQUEST_FROM_HASH containing the correct SHA from the commit on the source branch
 
Test 3:
RESCOPED activated
Change on target branch
Result: No trigger
Expected: Trigger with SHA for commit on target branch
 
Test 4:
RESCOPED_FROM activated
RESCOPED_TO activated
Change on target branch
Result: 2 triggers
Trigger 1: Correct trigger with PULL_REQUEST_FROM_HASH containing the correct SHA from the commit on the source branch
Trigger 2: Wrong trigger with PULL_REQUEST_FROM_HASH containing a SHA which is neither the SHA of the commit from the last commit on the source nor target branch 
Expected: 1 Trigger with PULL_REQUEST_FROM_HASH containing the correct SHA from the last commit on the source branch
 
Would be nice if you can have a look.
 
We use Stash 3.8.0 and plugin version 1.13

**Comment by christiangalsterer** [comment]
I did some further testing and it might be that everything works OK.
Test 3:
Q:Is RESCOPED the same as RESCOPED_FROM?

Test 4:
It may be that there were 2 PR and it this case 2 notifications where fully OK. I need to check on Monday when back in the office.

**Comment by tomasbjerre** [comment]
RESCOPED is not same as RESCOPED_FROM.

Stash only has the rescoped event. And that may happen when:
1 source and target is changed
2. Source changed
3. Target changed

The code will map these scenarios to:
1. rescoped
2. rescoped_from
3. Rescoped_to

So to be sure to be notified when source changes, one would need to check both "rescoped" and "rescoped_from".

I think that should be made clearer in the documentation.

**Comment by christiangalsterer** [comment]
Thanks for clarification. I will leave an update on Monday on my further check in test 4.

**Comment by tomasbjerre** [comment]
@christiangalsterer this is off topic =)
I just published this Jenkins plugin:
https://github.com/tomasbjerre/jenkins-violation-comments-to-stash-plugin
If you are using static code analyzers, and have the time to test it, that would be great =)

**Comment by christiangalsterer** [comment]
As promised I did some retesting on test case 3+4. 
Test 3:
After adding "RESCOPED" and "RESCOPED_FROM" in parallel. Notifications are send as expected.

Test 4:
Here indeed a second PR was available. There the two notifications were sent and also the SHAs were perfectly correct.

So in all, everything works as expected. 

W.r.t https://github.com/tomasbjerre/jenkins-violation-comments-to-stash-plugin
I try to look into (looks interesting), but I will leave for vacation this week, so sure how much time I still have.
