### ISSUE TITLE
Who issued an action?

### ISSUE THREAD

**Issue by SaschaHowe** [tomasbjerre/pull-request-notifier-for-stash#36]
Hey, 

great plugin! Thanks a lot. 

I wonder is there a way currently to find out who issued an action, or can it be added in one of the next releases? 

I'd like to notify about, who approved a pull request or added a comment - maybe something like ${PULL_REQUEST_ACTION_ISSUED_BY} Example: Bob (while Bob is not the creator of the pull request, he "only" approved / commented / declined the pull request)
Hope this makes sense ;)

Thanks again, keep up the great work. 

Greetings,
    Sascha

**Comment by tomasbjerre** [comment]
Yes that is possible! Seems like a simple thing to implement. I'll probably implement it withing a few days, or if someone creates a pull request for it.

**Comment by SaschaHowe** [comment]
awesome. Looking forward to it!

Greetings

**Comment by tomasbjerre** [comment]
I'm adding these variables to resolve this issue:
${PULL_REQUEST_USER_DISPLAY_NAME} Example: Some User
${PULL_REQUEST_USER_EMAIL_ADDRESS} Example: some.user@stash.domain
${PULL_REQUEST_USER_ID} Example: 1
${PULL_REQUEST_USER_NAME} Example: user.name
${PULL_REQUEST_USER_SLUG} Example: user.name

**Comment by tomasbjerre** [comment]
This is now in 1.14!

**Comment by SaschaHowe** [comment]
Hey, 

"Sascha Howe* APPROVED PULL-REQ: " 

works great. Thanks loads!
