### ISSUE TITLE
Pull Request Trigger Firing Twice

### ISSUE THREAD

**Issue by RBeaudoin** [tomasbjerre/pull-request-notifier-for-stash#37]
I am using this add on to trigger a build when a pull request is submitted, using this config:

![screen shot 2015-06-19 at 12 23 11 pm](https://cloud.githubusercontent.com/assets/2453382/8259979/020a870a-167e-11e5-894f-434daae12561.png)

It looks like on Pull Request creation my build is being triggered twice, and since it's only triggered via this plugin I'm assuming the plugin is making the POST request twice. If it's user config issue let me know what I need to change

**Comment by tomasbjerre** [comment]
You do want to also check the rescoped box. You current setup will not trigger if both source and target is changed at the exact same time. I should probably remove the rescoped box and have this behaviour as default.

The issue has been reported before, in https://github.com/tomasbjerre/pull-request-notifier-for-stash/issues/20 .

I would suggest that you have both from and to hash in the URL. And then check the log file of the notified system. To be absolutely certain that it gets notified twice.

Keep me posted :)

**Comment by tomasbjerre** [comment]
Updated means you will trigger on description or title change...

https://developer.atlassian.com/static/javadoc/stash.old-perms-pre-feb4/2.0.1/api/reference/com/atlassian/stash/event/pull/PullRequestUpdatedEvent.html

Do you really want to trigger a build for that?

**Comment by RBeaudoin** [comment]
@tomasbjerre I can remove 'Updated' that makes sense. In fact we should add that link to the README here so folks understand what triggers what in Stash.

I'll do some debugging and see what is triggering twice

**Comment by tomasbjerre** [comment]
Closing this one, to clean the issue list a bit. Re-open if still occurring.
