### ISSUE TITLE
Reply on Comment, doesn't trigger Commented event

### ISSUE THREAD

**Issue by SaschaHowe** [tomasbjerre/pull-request-notifier-for-stash#40]
Hey, 

just noticed the above and wanted to check if that's intentional behaviour.  

If "bug", possible solutions would be to trigger commented event also for replies or create a new event and fire that. 

Greetings

**Comment by tomasbjerre** [comment]
It should work for the comment event. There is an event in stash for reply: https://developer.atlassian.com/static/javadoc/stash.old-perms-pre-feb4/1.3.1/api/reference/com/atlassian/stash/event/pull/PullRequestCommentRepliedEvent.html

Im currently on vaccation and cannot look at it for a few weeks.

**Comment by tomasbjerre** [comment]
I just released 1.16 with this included.
