### ISSUE TITLE
"trigger build" button

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-stash#41]
is it me or pressing the "trigger build" button (available on a pull-request page, top-right corner) doesn't do anything?

i would've expected that with this plugin (and configured correctly), it would trigger an HTTP call (a Jenkins' notifyCommit to be specific)

**Comment by tomasbjerre** [comment]
You probably have the Jenkins Webhook plugin installed right? It adds that button.

Its not a feature added by this plugin and is not controlled by it.

**Comment by andreineculau** [comment]
oops! indeed!

is there a way though to trigger a build via your plugin, though? it's useful when you have intermittent issues, and want a re-run

**Comment by tomasbjerre** [comment]
Yes. You can have jenkins post a comment in the pull request. With a link that triggers the same build. A sample shellscript using curl is available here: 
http://bjurr.se/building-atlassian-stash-pull-requests-in-jenkins/

Or trigger a new build if someone writes a comment. And perhaps only if that comment contains something like "retrigger build".
