### ISSUE TITLE
Comments on closed/merged issues trigger Commented event

### ISSUE THREAD

**Issue by derekln1** [tomasbjerre/pull-request-notifier-for-stash#42]
Hi Tomas,

One of our users just saw that we can trigger a commented event on a pull request that has already been merged.  I was able to reproduce it.

When you get a chance, can you look into updating the hook to ignore commented events on a closed pull request?

Thanks,
Derek

**Comment by tomasbjerre** [comment]
Im not sure if this should be configurable or not. Perhaps I just add it without configuration and if someone complains I'll add configuration for it. What do you think?

**Comment by derekln1** [comment]
i think it's ok to add it without configuration.  I don't see a case where someone would want to trigger builds on a pull request that is in the Closed state.

Btw, also seeing builds for Closed pull requests getting triggered on RESCOPED_FROM events.

thanks

**Comment by tomasbjerre** [comment]
Released in version 1.17 =)

**Comment by derekln1** [comment]
Awesome.  Thanks Tomas!
