### ISSUE TITLE
Provide URL for Pull Request as parameter to be used in notification

### ISSUE THREAD

**Issue by christiangalsterer** [tomasbjerre/pull-request-notifier-for-stash#45]
Add the URL for the pull request as an additional parameter.
I'm currently implementing this and will provide a pull request.

**Comment by christiangalsterer** [comment]
PR is now available at https://github.com/tomasbjerre/pull-request-notifier-for-stash/pull/47

**Comment by christiangalsterer** [comment]
PR is available at https://github.com/tomasbjerre/pull-request-notifier-for-stash/pull/47

**Comment by tomasbjerre** [comment]
Nice, the PR is merged. Thanks!
