### ISSUE TITLE
MERGED event is not risen

### ISSUE THREAD

**Issue by mcgee** [tomasbjerre/pull-request-notifier-for-stash#48]
I've subscribed on all events and my url is invoked for most of them successfully. But the url is not invoked for MERGE event at all. Version of my Stash installation is  ``v3.11.1``

**Comment by tomasbjerre** [comment]
Most likely a bug introduced when implementing #42 . Will fix it as soon as I can.

**Comment by tomasbjerre** [comment]
Released in 1.19, open issue again if not solved!

**Comment by agsmorodin** [comment]
merge trigger does not work for me as well.  bitbucket version 4.9.1,  plugin version - 2.37.
rest of triggers work fine.

**Comment by tomasbjerre** [comment]
Do you see anything in the server logs? How did you configure the plugin?

**Comment by agsmorodin** [comment]
Another bitbucket plugin was blocking this trigger.  After disabling that plugin,  pr notifier started to work properly on merge event as well.
