### ISSUE TITLE
ids of HTML elements need to be unique

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-stash#50]
e.g. right now "BUTTON_TRIGGER_1" seems to be assigned to all "BUTTON_TRIGGER" checkboxes, meaning there are weird consequences when clicking the label on the 3rd rule's "BUTTON_TRIGGER", but the browser things you're interacting with the 1st rule's "BUTTON_TRIGGER"

**Comment by tomasbjerre** [comment]
Released in 1.21, open again if problem still not fixed.
