### ISSUE TITLE
trigger button should be hidden if no rule with BUTTON_TRIGGER event matches the PR

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-stash#51]
right now, adding a trigger button prnfs' admin page, means the button is added to all projects' and all PRs, although there button_trigger rule matches only one project, one repo, one branch, etc.

this creates confusion since devs of other projects, repos, etc think that they trigger an action, when in fact they don't

**Comment by tomasbjerre** [comment]
Released in 1.21, open again if problem still not fixed.

**Comment by andreineculau** [comment]
Fint! Tackar
