### ISSUE TITLE
Make PR Event available as a parameter

### ISSUE THREAD

**Issue by christiangalsterer** [tomasbjerre/pull-request-notifier-for-stash#54]
Make the PR event available as a parameter so that it can be used to further differentiate builds and/or use it in the trigger system to set the reason why the system was triggered.

Example 1: Set in the build description of a Jenkins job why the build was triggered.
Example 2: Triggered different build based on event type but only trigger one URL.

I think I can provide a PR in the next days.

**Comment by tomasbjerre** [comment]
Like OPENED or RESCOPED? The PULL_REQUEST_ACTION variable contains that string.

**Comment by christiangalsterer** [comment]
UPS, overlooked that, so issue can be closed.
