### ISSUE TITLE
bug: no POST content

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-stash#62]
upgraded to 1.22 crash
upgraded to 1.23 to fix the crash

POST content is not being sent now..

**Comment by tomasbjerre** [comment]
Which version did you use before 1.22?
You probably have a stack trace in the log, as in:
https://github.com/tomasbjerre/pull-request-notifier-for-stash/issues/61
I will fix it within 3 hours =)

**Comment by andreineculau** [comment]
afaics there isn't anything in the logs for this "no POST content" issue

previous version 1.21. i downgraded so take your time but:
don't know if atlassian market has the possibility to
mark-as-broken/withdraw addon versions but i'd do that for 1.22 and 1.23

On Tue, Sep 1, 2015 at 3:22 PM, Tomas Bjerre <notifications@github.com>
wrote:

> Which version did you use before 1.22?
> You probably have a stack trace in the log, as in:
> #61
> <https://github.com/tomasbjerre/pull-request-notifier-for-stash/issues/61>
> I will fix it within 3 hours =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomasbjerre/pull-request-notifier-for-stash/issues/62#issuecomment-136718860>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by tomasbjerre** [comment]
Did you try GET with v. 1.22 or 1.23? Did you try both GET and POST with 1.21?

**Comment by tomasbjerre** [comment]
Found it, fixed in 1.25. Open issue again if not solved.

**Comment by andreineculau** [comment]
Thanks, Tomas!
For now, I will keep to 1.21.
You could convince me to take the risk of upgrading by closing #55, #57 and
#58 :)

On Tue, Sep 1, 2015 at 7:09 PM, Tomas Bjerre <notifications@github.com>
wrote:

> Found it, fixed in 1.25. Open issue again if not solved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomasbjerre/pull-request-notifier-for-stash/issues/62#issuecomment-136799023>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by tomasbjerre** [comment]
Ok :)
