### ISSUE TITLE
[feature] disable a trigger if there are merge conflicts

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-stash#64]
currently I have 2 triggers per repo - one to test the pull-request source branch, and one to test the pull-request merge (re: #63) since it provides a closer-to-truth view on wether the merge should be allowed or not

could the trigger be disabled if the pull-request has merge conflicts?

NOTE: this is different than disabling the trigger if the merge button is disabled (it can be disabled for non-merge-conflict reasons - not enough approved reviewers, no enough permissions to merge, etc)

**Comment by tomasbjerre** [comment]
Perhaps adding radio buttons
* Trigger regardless of it can be merged (default)
* Trigger only if can be merged
* Trigger only if can not be merged

That would enable a user to
* trigger a merge and a simple build job
* just the merge job
* or just the simple build job

**Comment by andreineculau** [comment]
Music to my ears!

**Comment by tomasbjerre** [comment]
Released in 1.28:
https://github.com/tomasbjerre/pull-request-notifier-for-stash/releases/tag/pull-request-notifier-for-stash-1.28
Can you test it manually before I release it to Atlassian Marketplace?

**Comment by tomasbjerre** [comment]
Released it to Marketplace, open issue again if not working!
