### ISSUE TITLE
[feature] new parameter PULL_REQUEST_TITLE

### ISSUE THREAD

**Issue by andreineculau** [tomasbjerre/pull-request-notifier-for-stash#65]
so that you can see that in the CI, otherwise you only have the pull request author & id/url to map a CI run to a pull request/ticket

**Comment by tomasbjerre** [comment]
Released in 1.28:
https://github.com/tomasbjerre/pull-request-notifier-for-stash/releases/tag/pull-request-notifier-for-stash-1.28
Can you test it manually before I release it to Atlassian Marketplace?

**Comment by andreineculau** [comment]
Tomas, that's great! Thanks
I'm unfortunately not going to be able to test this until a week from now :(

**Comment by tomasbjerre** [comment]
Released it to Marketplace, open issue again if not working!
