### ISSUE TITLE
[enhancement] Trigger Button, connected to which trigger?

### ISSUE THREAD

**Issue by dozepih** [tomasbjerre/pull-request-notifier-for-stash#66]
Having several triggers for different repos makes it kind of difficult to know which trigger button corresponds to which trigger. Could perhaps the section handling the individual trigger button be integrated together and with the trigger chuck?

**Comment by tomasbjerre** [comment]
You are talking about the buttons in the admin GUI? Problem is that a button may trigger several notifications.

**Comment by dozepih** [comment]
Yes, in the admin GUI but I think I have it sorted now. I misunderstood.

**Comment by tomasbjerre** [comment]
Ok, can the issue be closed?

**Comment by dozepih** [comment]
Yes,  you can close it. Thanks!
